const SUPABASE_URL='https://qjqqpqogoxgjricazrtj.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqcXFwcW9nb3hnanJpY2F6cnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyNzQzMDIsImV4cCI6MjA5Nzg1MDMwMn0.CGVLLoC1wODvUB9cdw1o5T43MTGW8jplVIY-QQxc0yM';
const TEACHER_PIN='1234';
const hasSupabase=!SUPABASE_URL.includes('COLE_AQUI')&&!SUPABASE_ANON_KEY.includes('COLE_AQUI');
const sb=hasSupabase?window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const LS={user:'uc03_user_v3',mode:'uc03_global_mode',scores:'uc03_scores_v3',answered:'uc03_answered_v3',teacher:'uc03_teacher_v3',settings:'uc03_settings_v3'};
const defaultSettings={mode:'historia',activities:{diagnostico:true,anatomia:true,consultoria:true,missoes:true},releasedCases:Array.from({length:50},(_,i)=>i+1)};
let state={user:null,settings:load(LS.settings,defaultSettings),currentPage:'home',currentCase:null,currentHint:1,arena:{round:0,hint:0,case:null,student:null,next:null}};
const students=['Ana Luiza','Carlos','Rafael','João Vitor','Guilherme','Maria Gabriele','Victor','Levi','Linara','Yan','Nicoly','Karol','Lara','Karen','Gabriel','Vinicius'];
const consulting={
'Ana Luiza':['Clínica Odontológica Sorriso+','R$ 6.800','Computador para recepção e apoio clínico. Uso com sistema odontológico, radiografias digitais, documentos, videochamadas e organização administrativa.'],
'Carlos':['Escritório de Engenharia Civil','R$ 11.500','Máquina para projetos técnicos, plantas, modelagem e visualização arquitetônica.'],
'Rafael':['Streamer Gamer','R$ 13.500','Estação para transmissões ao vivo, jogos AAA, edição de cortes e uso de OBS, Discord e softwares de captura.'],
'João Vitor':['Empresa de Monitoramento','R$ 7.500','Central de monitoramento com funcionamento prolongado e múltiplas telas.'],
'Guilherme':['Desenvolvedor Full Stack','R$ 9.200','Programação, containers, bancos de dados, emuladores e ambientes de teste.'],
'Maria Gabriele':['Designer Gráfico','R$ 9.800','Criação visual, edição de imagens, identidade visual e produção de peças digitais.'],
'Victor':['Empresa de Contabilidade','R$ 5.900','Rotinas fiscais, planilhas, documentos, sistemas web e impressão.'],
'Levi':['Arquiteto 3D','R$ 14.500','Modelagem arquitetônica, renderização e visualização 3D.'],
'Linara':['Escola Particular','R$ 4.800','Laboratório de informática, aulas práticas, navegação, digitação e programação básica.'],
'Yan':['Editor de Vídeo','R$ 12.000','Edição com múltiplas camadas, efeitos, correção de cor e exportação frequente.'],
'Nicoly':['Consultório Médico','R$ 7.300','Prontuário eletrônico, teleatendimento, documentos, exames simples e segurança.'],
'Karol':['Agência de Marketing','R$ 8.500','Posts, anúncios, apresentações, imagens com IA, relatórios e materiais comerciais.'],
'Lara':['Influenciadora Digital','R$ 10.500','Criação de vídeos, transmissões, edição de conteúdos curtos e IA.'],
'Karen':['Home Lab','R$ 9.800','Servidor doméstico para virtualização, NAS, containers e serviços internos.'],
'Gabriel':['Cyber Café Gamer','R$ 15.000','Jogos competitivos, upgrade, refrigeração, estética e alto FPS.'],
'Vinicius':['Pesquisador em IA','R$ 18.000','Python, machine learning, modelos locais, CUDA e virtualização.']
};
const baseCases=[
['Computador não liga','Nenhum LED acende.','Tomada e cabo funcionam em outro equipamento.','Fonte de alimentação, cabo, botão power ou placa-mãe.'],
['Liga, mas não aparece imagem','Coolers giram e LEDs acendem.','Ao recolocar a RAM, às vezes volta vídeo.','Memória RAM mal encaixada ou com defeito.'],
['Desliga após alguns minutos','Gabinete fica muito quente.','CPU chega perto de 95°C.','Superaquecimento, cooler, pasta térmica ou fluxo de ar.'],
['Mensagem No Boot Device','BIOS abre normalmente.','SSD não aparece na ordem de boot.','SSD/HD, cabo SATA, M.2, ordem de boot ou sistema.'],
['Tela azul frequente','Reinicia durante o uso.','Ocorre mais em multitarefa.','RAM, driver, sistema corrompido ou disco.'],
['Monitor sem sinal','Outro monitor funciona.','Cabo HDMI apresenta mau contato.','Cabo ou porta de vídeo.'],
['Computador muito lento','Programas levam minutos.','Disco fica em 100%.','HD degradado, processos, malware ou pouca RAM.'],
['USB frontal não funciona','Portas traseiras funcionam.','Cabo interno USB está solto.','Conector USB frontal ou header da placa-mãe.'],
['Internet não acessa','Wi-Fi conectado.','DNS não responde.','DNS, gateway, roteador ou configuração de rede.'],
['Notebook sem imagem interna','Monitor externo exibe vídeo.','Tela interna permanece apagada.','Tela LCD, flat cable ou backlight.']
];
const cases=Array.from({length:50},(_,i)=>{const b=baseCases[i%baseCases.length];return{id:i+1,title:`Caso ${String(i+1).padStart(2,'0')}`,pistas:[b[0],b[1],b[2]],answer:b[3]}});
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function $(id){return document.getElementById(id)}
function show(el){el.classList.remove('hidden')}function hide(el){el.classList.add('hidden')}
function init(){state.user=load(LS.user,null);setupIdentity();setupNav();setupForms();renderAll(); if(state.user){hide($('loginScreen'));show($('app'))}else{show($('loginScreen'));hide($('app'))}}
function setupIdentity(){const ret=$('returningCard'),form=$('identityForm');if(state.user){$('returningTitle').textContent=`Continuar como ${state.user.name}`;$('returningMeta').textContent=`Turma: ${state.user.turma}`;show(ret);hide(form)}$('continueBtn').onclick=()=>{hide($('loginScreen'));show($('app'));renderAll()};$('changeUserBtn').onclick=()=>{localStorage.removeItem(LS.user);state.user=null;hide(ret);show(form)};form.onsubmit=e=>{e.preventDefault();const name=$('studentName').value.trim();if(!name)return;state.user={name,turma:$('studentClass').value};save(LS.user,state.user);hide($('loginScreen'));show($('app'));renderAll()};$('logoutBtn').onclick=()=>{localStorage.removeItem(LS.user);location.reload()}}
function setupNav(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>go(b.dataset.jump))}
function go(page){if(page!=='home'&&page!=='ranking'&&page!=='conquistas'&&page!=='professor'&&state.settings.mode==='arena'){alert('Modo Arena ativo. As atividades individuais estão bloqueadas.');return}document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(page).classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));state.currentPage=page;if(page==='diagnostico')loadNextCase();renderAll()}
function setupForms(){for(let i=1;i<=39;i++)$('componentNumber').insertAdjacentHTML('beforeend',`<option>${i}</option>`);
$('revealHintBtn').onclick=()=>{if(state.currentHint<3){state.currentHint++;renderCase()}};
$('diagnosisForm').onsubmit=async e=>{e.preventDefault();if(isArena())return alert('Modo Arena ativo.');const key=`${state.user.name}|diagnostico|${state.currentCase.id}`;const answered=load(LS.answered,{});if(answered[key])return msg('diagStatusMsg','Caso já respondido.','warn');answered[key]=true;save(LS.answered,answered);await insert('respostas_diagnostico',{aluno:state.user.name,turma:state.user.turma,caso_id:state.currentCase.id,pista_usada:state.currentHint,diagnostico:$('diagAnswer').value,possiveis_causas:$('diagCauses').value,como_testar:$('diagTest').value,pontos_auto:Math.max(6,11-state.currentHint)});addScore('diagnostico',Math.max(6,11-state.currentHint));e.target.reset();msg('diagStatusMsg','Resposta enviada. Caso bloqueado para este aluno.','ok');loadNextCase()};
$('anatomiaForm').onsubmit=async e=>{e.preventDefault();if(isArena())return alert('Modo Arena ativo.');const comp=$('componentNumber').value;const key=`${state.user.name}|anatomia|${comp}`;const answered=load(LS.answered,{});if(answered[key])return msg('anatStatusMsg','Componente já enviado.','warn');answered[key]=true;save(LS.answered,answered);await insert('respostas_anatomia',{aluno:state.user.name,turma:state.user.turma,componente_numero:+comp,nome:$('componentName').value,funcao:$('componentFunction').value,defeitos:$('componentDefects').value,sintomas:$('componentSymptoms').value,como_testar:$('componentTest').value,pontos_auto:2});addScore('anatomia',2);e.target.reset();msg('anatStatusMsg','Componente salvo.','ok')};
$('consultForm').onsubmit=async e=>{e.preventDefault();if(isArena())return alert('Modo Arena ativo.');const key=`${state.user.name}|consultoria|principal`;const answered=load(LS.answered,{});if(answered[key])return msg('consultStatusMsg','Consultoria já enviada. Peça ao professor para reabrir, se necessário.','warn');answered[key]=true;save(LS.answered,answered);await insert('entregas_consultoria_hardware',{aluno:state.user.name,turma:state.user.turma,link_planilha:$('sheetLink').value,link_canva:$('canvaLink').value,observacoes:$('consultObs').value});addScore('consultoria',10);e.target.reset();msg('consultStatusMsg','Entrega registrada. Aguardando avaliação final do professor.','ok')};
$('teacherLoginBtn').onclick=()=>{if($('teacherPin').value===TEACHER_PIN){save(LS.teacher,true);renderTeacher()}else alert('PIN incorreto')};$('teacherLogoutBtn').onclick=()=>{localStorage.removeItem(LS.teacher);renderTeacher()};$('globalArenaToggle').onchange=e=>{state.settings.mode=e.target.checked?'arena':'historia';save(LS.settings,state.settings);renderAll()};$('drawArenaBtn').onclick=drawArena;$('nextArenaHintBtn').onclick=()=>{if(state.arena.case&&state.arena.hint<3){state.arena.hint++;renderArena()}};$('passArenaBtn').onclick=()=>{drawArena(true)};$('fillEvalBtn').onclick=()=>{if(state.arena.student){$('manualStudent').value=state.arena.student;$('manualActivity').value='diagnostico';$('manualPoints').value=state.arena.hint===1?10:state.arena.hint===2?8:6}};$('manualScoreForm').onsubmit=async e=>{e.preventDefault();await insert('pontuacoes_manuais',{aluno:$('manualStudent').value,turma:$('manualClass').value,atividade:$('manualActivity').value,pontos:+$('manualPoints').value,comentario:$('manualComment').value});addScoreFor($('manualStudent').value,$('manualActivity').value,+$('manualPoints').value);msg('manualStatusMsg','Pontuação lançada.','ok');e.target.reset();renderAll()};$('refreshRankingBtn').onclick=renderRanking;$('refreshRankingHome').onclick=renderRanking;$('refreshResponsesBtn').onclick=renderResponses}
async function insert(table,payload){if(!hasSupabase)return true;const {error}=await sb.from(table).insert(payload);if(error){console.error(error);alert('Erro no Supabase. Verifique tabela/RLS.')}return !error}
function isArena(){return state.settings.mode==='arena'}
function renderAll(){if(!state.user)return;renderHeader();renderLocks();renderConsulting();renderMissions();renderBadges();renderRanking();renderTeacher()}
function renderHeader(){$('welcomeName').textContent=`Bem-vindo(a), ${state.user.name}`;$('welcomeClass').textContent=`Turma: ${state.user.turma}`;const s=scoresFor(state.user.name);$('xpDiag').textContent=s.diagnostico||0;$('xpAnat').textContent=s.anatomia||0;$('xpCons').textContent=s.consultoria||0;$('xpExtra').textContent=s.extra||0;$('xpTotal').textContent=`${Object.values(s).reduce((a,b)=>a+b,0)} XP`;$('modeBadge').textContent=isArena()?'Arena':'História';$('modeBadge').className=isArena()?'':'success';$('arenaNotice').classList.toggle('hidden',!isArena())}
function renderLocks(){document.querySelectorAll('.student-module').forEach(b=>b.classList.toggle('locked',isArena()));['diag','anatomia','consultoria'].forEach(prefix=>{const block=$(prefix+'Blocked'),play=$(prefix+'Play'); if(block&&play){block.classList.toggle('hidden',!isArena());play.classList.toggle('hidden',isArena())}})}
function loadNextCase(){if(isArena())return;const answered=load(LS.answered,{});const next=cases.find(c=>state.settings.releasedCases.includes(c.id)&&!answered[`${state.user.name}|diagnostico|${c.id}`]);state.currentCase=next||cases[0];state.currentHint=1;renderCase()}
function renderCase(){if(!state.currentCase)return; $('caseTitle').textContent=`${state.currentCase.title} · ${state.currentCase.pistas[0]}`;$('caseStatus').textContent=`Pista ${state.currentHint}`;$('pistasBox').innerHTML=state.currentCase.pistas.slice(0,state.currentHint).map((p,i)=>`<div class="hint"><strong>Pista ${i+1}</strong><br>${p}</div>`).join('');$('revealHintBtn').disabled=state.currentHint>=3}
function renderConsulting(){const c=consulting[state.user.name]||['Cliente Técnico','R$ 8.000','Defina uma configuração compatível com a necessidade recebida.'];$('studentConsultingCase').innerHTML=`<h3>${c[0]}</h3><span class="budget">${c[1]}</span><p>${c[2]}</p><ul><li>Pesquisar peças reais com links.</li><li>Respeitar orçamento.</li><li>Justificar compatibilidade e prazo.</li><li>Preparar defesa oral.</li></ul>`}
function renderMissions(){const missions=[['Acertar 5 diagnósticos','+30 XP'],['Identificar 10 componentes','+30 XP'],['Entregar consultoria','+50 XP'],['Participar da Arena','+20 XP']];$('missionsGrid').innerHTML=missions.map(m=>`<article class="course-card"><span>🧩</span><h3>${m[0]}</h3><p>Missão de aula ou laboratório.</p><strong>${m[1]}</strong></article>`).join('')}
function renderBadges(){const badges=['Mestre da RAM','Especialista em SSD','Caçador de BSOD','Consultor de Hardware','Anatomia Expert','Técnico Master'];$('badgesGrid').innerHTML=badges.map(b=>`<article class="course-card"><span>🏅</span><h3>${b}</h3><p>Conquista liberada conforme desempenho.</p></article>`).join('')}
function renderRanking(){const scores=load(LS.scores,{});let rows=Object.entries(scores).map(([name,v])=>({name,total:Object.values(v).reduce((a,b)=>a+b,0),turma:v.turma||'UC03 Manutenção'})).sort((a,b)=>b.total-a.total);if(rows.length===0&&state.user)rows=[{name:state.user.name,turma:state.user.turma,total:0}];const html=rows.map((r,i)=>`<div class="rank-row"><div>${i===0?'🥇':i===1?'🥈':i===2?'🥉':'#'+(i+1)}</div><div><strong>${r.name}</strong><br><small>${r.turma}</small></div><strong>${r.total} XP</strong></div>`).join('');$('rankingPodium').innerHTML=html;$('rankingFull').innerHTML=html}
function renderTeacher(){const logged=load(LS.teacher,false);$('profLogin').classList.toggle('hidden',logged);$('profPanel').classList.toggle('hidden',!logged);if(!logged)return;$('globalArenaToggle').checked=isArena();$('teacherModeText').innerHTML=isArena()?'<strong>Modo Arena ativo.</strong> Alunos bloqueados nas atividades individuais.':'<strong>Modo História ativo.</strong> Alunos respondem individualmente.';$('activityToggles').innerHTML=Object.entries(state.settings.activities).map(([k,v])=>`<div class="toggle-item"><span>${label(k)}</span><input type="checkbox" ${v?'checked':''} data-act="${k}"></div>`).join('');document.querySelectorAll('[data-act]').forEach(i=>i.onchange=e=>{state.settings.activities[e.target.dataset.act]=e.target.checked;save(LS.settings,state.settings);renderAll()});renderArena();renderResponses()}
function drawArena(pass=false){state.arena.round++;state.arena.student=pass?state.arena.next||pick(students):pick(students);state.arena.next=pick(students.filter(s=>s!==state.arena.student));state.arena.case=pick(cases.filter(c=>state.settings.releasedCases.includes(c.id)));state.arena.hint=1;renderArena()}
function renderArena(){$('arenaRoundBadge').textContent=`Rodada ${state.arena.round}`;$('arenaStudent').textContent=state.arena.student||'Aguardando';$('arenaNext').textContent=state.arena.next||'--';$('arenaCase').textContent=state.arena.case?state.arena.case.title:'--';$('arenaHint').textContent=state.arena.hint||'--';$('arenaQuestion').innerHTML=state.arena.case?`<strong>${state.arena.case.pistas[0]}</strong><br>${state.arena.case.pistas.slice(1,state.arena.hint).map((p,i)=>`<br><strong>Pista ${i+2}:</strong> ${p}`).join('')}`:'Nenhuma rodada sorteada.'}
function renderResponses(){const rows=load('uc03_local_responses',[]);$('responsesTable').innerHTML=rows.slice(-20).reverse().map(r=>`<tr><td>${r.aluno}</td><td>${r.ref||'-'}</td><td>${r.text||'-'}</td><td>${r.xp||0}</td><td>${r.data||'-'}</td><td><button class="btn small">Ver</button></td></tr>`).join('')||'<tr><td colspan="6">Nenhuma resposta local registrada. Com Supabase configurado, os dados virão do banco.</td></tr>'}
function addScore(activity,points){addScoreFor(state.user.name,activity,points)}
function addScoreFor(name,activity,points){const scores=load(LS.scores,{});scores[name]=scores[name]||{turma:state.user?.turma||'UC03 Manutenção',diagnostico:0,anatomia:0,consultoria:0,extra:0};const key=activity==='anatomia'?'anatomia':activity==='consultoria'?'consultoria':activity==='extra'?'extra':'diagnostico';scores[name][key]=(scores[name][key]||0)+points;save(LS.scores,scores);renderAll()}
function scoresFor(name){const s=load(LS.scores,{});return s[name]||{diagnostico:0,anatomia:0,consultoria:0,extra:0}}
function msg(id,text,type){const el=$(id);el.textContent=text;el.style.color=type==='ok'?'#86efac':type==='warn'?'#fed7aa':'#fecaca'}
function label(k){return({diagnostico:'Diagnóstico',anatomia:'Anatomia',consultoria:'Consultoria',missoes:'Missões'})[k]||k}
function pick(arr){return arr[Math.floor(Math.random()*arr.length)]}
init();
